source("C:/Estudos/Entrada CD/lancamento/import.R")
gc()
source("C:/Estudos/Entrada CD/lancamento/geracao.R")
gc()
source("C:/Estudos/Entrada CD/lancamento/export.R")
gc()
source("C:/Estudos/Entrada CD/lancamento/email.R")
gc()