library(dplyr)
library(stringr)
library(lubridate)
library(RODBC)
library(zoo)

con <- RODBC::odbcDriverConnect('driver={SQL Server} ;server=cosmos;database=cosmos_v14b')

# Consultas ####

# Venda Media dia ====
vmd <- str_c("
SET DATEFORMAT DMY
DECLARE @DATA01 VARCHAR(10)
DECLARE @DATA02 VARCHAR(10)
DECLARE @DATA03 VARCHAR(10)
DECLARE @DATA04 VARCHAR(10)
DECLARE @DATA05 VARCHAR(10)
DECLARE @DATA06 VARCHAR(10)
DECLARE @DATA07 VARCHAR(10)
SET @DATA01= CONVERT(VARCHAR(10),DATEADD(DAY,-181,GETDATE()),103)
SET @DATA02= CONVERT(VARCHAR(10),DATEADD(DAY,30,@DATA01),103)
SET @DATA03= CONVERT(VARCHAR(10),DATEADD(DAY,30,@DATA02),103)
SET @DATA04= CONVERT(VARCHAR(10),DATEADD(DAY,30,@DATA03),103)
SET @DATA05= CONVERT(VARCHAR(10),DATEADD(DAY,30,@DATA04),103)
SET @DATA06= CONVERT(VARCHAR(10),DATEADD(DAY,30,@DATA05),103)
SET @DATA07= CONVERT(VARCHAR(10),DATEADD(DAY,30,@DATA06),103)
    
;WITH DMDDIALOJA (CD, CODPROD, DMDDIA) AS
(      
	SELECT
		T1.CD,
		T1.CODPROD,
		CAST(SUM(CASE 
					WHEN (T1.DT_OCORR_REAL>@DATA01+' 23:59:59' AND T1.DT_OCORR_REAL<=@DATA02+' 23:59:59') 
					AND T1.QTDVENDA>0 THEN T1.QTDVENDA*0.03
					WHEN (T1.DT_OCORR_REAL>@DATA02+' 23:59:59' AND T1.DT_OCORR_REAL<=@DATA03+' 23:59:59') 
					AND T1.QTDVENDA>0 THEN T1.QTDVENDA*0.07
					WHEN (T1.DT_OCORR_REAL>@DATA03+' 23:59:59' AND T1.DT_OCORR_REAL<=@DATA04+' 23:59:59') 
					AND T1.QTDVENDA>0 THEN T1.QTDVENDA*0.1
					WHEN (T1.DT_OCORR_REAL>@DATA04+' 23:59:59' AND T1.DT_OCORR_REAL<=@DATA05+' 23:59:59') 
					AND T1.QTDVENDA>0 THEN T1.QTDVENDA*0.2
					WHEN (T1.DT_OCORR_REAL>@DATA05+' 23:59:59' AND T1.DT_OCORR_REAL<=@DATA06+' 23:59:59') 
					AND T1.QTDVENDA>0 THEN T1.QTDVENDA*0.27
					WHEN (T1.DT_OCORR_REAL>@DATA06+' 23:59:59' AND T1.DT_OCORR_REAL<=@DATA07+' 23:59:59') 
					AND T1.QTDVENDA>0 THEN T1.QTDVENDA*0.33
					ELSE 0 
		END)/30 AS DECIMAL(20,6)) AS DMDDIA
    
	FROM (SELECT
			FL.CODIGO_DEPOSITO_PRINCIPAL AS CD
            ,KF.KAFI_CD_FILIAL AS FILIAL
            ,KF.KAFI_CD_PRODUTO AS CODPROD
            ,KF.KAFI_QT_MOV AS QTDVENDA
            ,KF.KAFI_DH_OCORRREAL AS DT_OCORR_REAL
        
		FROM KARDEX_FILIAL KF WITH(NOLOCK)
        
		INNER JOIN PRODUTO_MESTRE PM WITH(NOLOCK)
        ON KF.KAFI_CD_PRODUTO = PM.PRME_CD_PRODUTO
        INNER JOIN FILIAL FL WITH(NOLOCK)
        ON KF.KAFI_CD_FILIAL = FL.FILI_CD_FILIAL
        
		WHERE 
			KF.KAFI_TP_MOV IN('SV')
            AND KF.KAFI_DH_OCORRREAL BETWEEN 
            @DATA01+' 23:59:59' AND @DATA07+' 23:59:59'
			AND PM.XXXX_DH_CAD <@DATA01+' 00:00:00' AND FL.XXXX_DH_CAD <@DATA01+' 00:00:00'
			AND (PM.CAPN_CD_CATEGORIA NOT LIKE '3%'
			AND PM.CAPN_CD_CATEGORIA NOT LIKE '1.101.009%'
			AND PM.CAPN_CD_CATEGORIA NOT LIKE '1.102.009%'
			AND PM.CAPN_CD_CATEGORIA NOT LIKE '2.504.001%')

		UNION ALL

		SELECT
			FL.CODIGO_DEPOSITO_PRINCIPAL AS CD
			,KFD.KAFI_CD_FILIAL AS FILIAL
			,KFD.KAFI_CD_PRODUTO AS CODPROD
			,KFD.KAFI_QT_MOV AS QTDVENDA
			,KFD.KAFI_DH_OCORRREAL AS DT_OCORR_REAL
		FROM KARDEX_FILIAL_DIA KFD WITH(NOLOCK)
    
		INNER JOIN PRODUTO_MESTRE PM WITH(NOLOCK)
		ON KFD.KAFI_CD_PRODUTO = PM.PRME_CD_PRODUTO
		INNER JOIN FILIAL FL WITH(NOLOCK)
		ON KFD.KAFI_CD_FILIAL = FL.FILI_CD_FILIAL
    
		WHERE 
			KFD.KAFI_TP_MOV IN('SV')
			AND KFD.KAFI_DH_OCORRREAL BETWEEN @DATA01+' 23:59:59' AND @DATA07+' 23:59:59'
			AND PM.XXXX_DH_CAD <@DATA01+' 00:00:00' AND FL.XXXX_DH_CAD <@DATA01+' 00:00:00'
			AND (PM.CAPN_CD_CATEGORIA NOT LIKE '3%'
			AND PM.CAPN_CD_CATEGORIA NOT LIKE '1.101.009%'
			AND PM.CAPN_CD_CATEGORIA NOT LIKE '1.102.009%'
			AND PM.CAPN_CD_CATEGORIA NOT LIKE '2.504.001%')
	) AS T1
	GROUP BY
	T1.CD,
	T1.CODPROD
)

SELECT * FROM DMDDIALOJA", pattern = " ") 

#consulta base deposito ====

dep <- str_c("SELECT 
PD.DEPO_CD_DEPOSITO AS CD_DEP,
PD.PRME_CD_PRODUTO AS CD_PRODUTO,
CONVERT(DATE, PD.PRDP_DT_ULTCOMPRA) AS DT_ULTCOMPRA,
CAST(PD.PRDP_QT_ESTOQATUAL AS NUMERIC) AS QT_ESTQATUAL,
CAST(PD.PRDP_VL_CMPG AS NUMERIC) AS VL_CMPG,
CAST(PD.PRDP_QT_ESTOQATUAL * PD.PRDP_VL_CMPG AS MONEY) AS VL_ESTATUAL,
PD.PRDP_TP_CLABCFAT AS TP_ABC,
pd.PRDP_FL_SITUACAO as FL_SITUACAO

FROM PRODUTO_DEPOSITO PD

INNER JOIN PRODUTO_MESTRE PM WITH(NOLOCK)
ON PD.PRME_CD_PRODUTO = PM.PRME_CD_PRODUTO

WHERE
PD.PRDP_QT_ESTOQATUAL > 0
AND PM.CAPN_CD_CATEGORIA NOT LIKE '3%'
AND PM.CAPN_CD_CATEGORIA NOT LIKE '1.101.009%'
AND PM.CAPN_CD_CATEGORIA NOT LIKE '1.102.009%'
AND PM.CAPN_CD_CATEGORIA NOT LIKE '2.504.001%'", pattern = " ")

# alternativa pme ====
cd_pme <- str_c("DECLARE @DATA01 DATE
  DECLARE @DATA02 DATE
  DECLARE @DATA03 DATE
  DECLARE @DATA04 DATE
  DECLARE @DATA05 DATE
  DECLARE @DATA06 DATE
  DECLARE @DATA07 DATE
  SET @DATA01= DATEADD(DAY,-181,GETDATE())
  SET @DATA02= DATEADD(DAY,30,@DATA01)
  SET @DATA03= DATEADD(DAY,30,@DATA02)
  SET @DATA04= DATEADD(DAY,30,@DATA03)
  SET @DATA05= DATEADD(DAY,30,@DATA04)
  SET @DATA06= DATEADD(DAY,30,@DATA05)
  SET @DATA07= DATEADD(DAY,30,@DATA06)
  
  SELECT
  	T1.CD
  	,T1.Produto
    ,CAST( SUM(
		CASE 
            WHEN (T1.DT_OCORR_REAL > @DATA01 AND T1.DT_OCORR_REAL <= @DATA02) 
            AND T1.QTDVENDA > 0 THEN T1.QTDVENDA  *0.03
            WHEN (T1.DT_OCORR_REAL > @DATA02 AND T1.DT_OCORR_REAL <= @DATA03) 
            AND T1.QTDVENDA > 0 THEN T1.QTDVENDA*0.07
            WHEN (T1.DT_OCORR_REAL > @DATA03  AND T1.DT_OCORR_REAL <= @DATA04) 
            AND T1.QTDVENDA>0 THEN T1.QTDVENDA*0.1
            WHEN (T1.DT_OCORR_REAL > @DATA04 AND T1.DT_OCORR_REAL <= @DATA05) 
            AND T1.QTDVENDA>0 THEN T1.QTDVENDA*0.2
            WHEN (T1.DT_OCORR_REAL>@DATA05 AND T1.DT_OCORR_REAL<=@DATA06) 
            AND T1.QTDVENDA>0 THEN T1.QTDVENDA*0.27
            WHEN (T1.DT_OCORR_REAL>@DATA06 AND T1.DT_OCORR_REAL<=@DATA07) 
            AND T1.QTDVENDA>0 THEN T1.QTDVENDA*0.33
            ELSE 0 
		END)/30 AS DECIMAL(20,6)) AS VMD

  FROM (
  	SELECT
  	      FL.CODIGO_DEPOSITO_PRINCIPAL AS CD
          ,KF.KAFI_CD_PRODUTO AS Produto
          ,KF.KAFI_QT_MOV AS QTDVENDA
          ,CONVERT(DATE, KF.KAFI_DH_OCORRREAL) AS DT_OCORR_REAL
      FROM KARDEX_FILIAL KF WITH(NOLOCK)
              
      INNER JOIN PRODUTO_MESTRE PM WITH(NOLOCK)
      ON KF.KAFI_CD_PRODUTO = PM.PRME_CD_PRODUTO
      INNER JOIN FILIAL FL WITH(NOLOCK)
      ON KF.KAFI_CD_FILIAL = FL.FILI_CD_FILIAL
              
      WHERE 
          KF.KAFI_TP_MOV IN('SV')
          AND CONVERT(DATE, KF.KAFI_DH_OCORRREAL) BETWEEN 
          @DATA01 AND @DATA07
          AND CONVERT(DATE,PM.XXXX_DH_CAD) < @DATA01 AND CONVERT(DATE,FL.XXXX_DH_CAD) < @DATA01
          AND PM.CAPN_CD_CATEGORIA NOT LIKE '3%'
          AND PM.CAPN_CD_CATEGORIA NOT LIKE '1.101.009%'
          AND PM.CAPN_CD_CATEGORIA NOT LIKE '1.102.009%'
          AND PM.CAPN_CD_CATEGORIA NOT LIKE '2.504.001%'
  
  	UNION ALL
  
  	SELECT
  		FL.CODIGO_DEPOSITO_PRINCIPAL AS CD
  		,KFD.KAFI_CD_PRODUTO AS CODPROD
  		,KFD.KAFI_QT_MOV AS QTDVENDA
  		,KFD.KAFI_DH_OCORRREAL AS DT_OCORR_REAL
  	FROM KARDEX_FILIAL_DIA KFD WITH(NOLOCK)
          
  	INNER JOIN PRODUTO_MESTRE PM WITH(NOLOCK)
  	ON KFD.KAFI_CD_PRODUTO = PM.PRME_CD_PRODUTO
  	INNER JOIN FILIAL FL WITH(NOLOCK)
  	ON KFD.KAFI_CD_FILIAL = FL.FILI_CD_FILIAL
          
  	WHERE 
  		KFD.KAFI_TP_MOV IN('SV')
  		AND CONVERT(DATE,KFD.KAFI_DH_OCORRREAL) BETWEEN @DATA01 AND @DATA07
  		AND CONVERT(DATE,PM.XXXX_DH_CAD) <@DATA01 AND FL.XXXX_DH_CAD <@DATA01
  		AND PM.CAPN_CD_CATEGORIA NOT LIKE '3%'
  		AND PM.CAPN_CD_CATEGORIA NOT LIKE '1.101.009%'
  		AND PM.CAPN_CD_CATEGORIA NOT LIKE '1.102.009%'
  		AND PM.CAPN_CD_CATEGORIA NOT LIKE '2.504.001%'
  
  ) T1

GROUP BY
	T1.CD
	,T1.Produto", pattern = " ")


# Extração ####

base_vmd <- sqlQuery(con, vmd)
base_dep <- sqlQuery(con, dep)

head(base_dep)
head(base_vmd)


between()
typeof(base_dep$DT_ULTCOMPRA)

base_dep$DT_ULTCOMPRA <- as.Date(base_dep$DT_ULTCOMPRA)

hoje <- today()

base <- base_dep %>%
  left_join(base_vmd, by = c("CD_DEP"="CD", "CD_PRODUTO"="CODPROD"))%>%
  mutate(
    PME = (QT_ESTQATUAL/DMDDIA)*30,
    AGING = round((as.yearmon(hoje) - as.yearmon(DT_ULTCOMPRA))*12,0),
    #faixa pme
    FAIXA_PME = ifelse(
      is.na(PME), "SV",
      ifelse(
        between(PME, 0,3), "0 - 3",
        ifelse(
          between(PME, 3,6), "3 - 6",
          ifelse(
            between(PME, 6, 9), "6 - 9",
            ifelse(
              between(PME, 9, 12), "9 - 12", "> 12"
             )
          )
        )
      )
    ),
    FAIXA_AGING = ifelse(
      is.na(AGING), "NaoEnc",
      ifelse(
        between(AGING, 0,3), "0 - 3",
        ifelse(
          between(AGING, 4,6), "3 - 6",
          ifelse(
            between(AGING, 7, 9), "6 - 9",
            ifelse(
              between(AGING, 9, 12), "10 - 12", "> 12"
            )
          )
        )
      )
    )
  )

write.csv2(base, "C:/Users/113024/paguemenos.com.br/Time Perda Conhecida - General/Pablo/Análises/Aging/bases/base.csv", row.names = F)
